packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.19.0
  prettier: ^3.4.2
  typescript: ^5.7.3
  husky: ^9.1.7
  lint-staged: ^15.4.3
  tailwindcss: 3.4.4
  nativewind: ^4.1.23

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  jest29:
    "@jest/globals": ^29.7.0
    "@types/jest": ^29.5.14
    jest: 29.7.0
    ts-jest: ^29.2.5
